package ve.com.digitel.key;


public enum Key 
{
	
	REQUEST, 
	RESPONSE, 
	//RECHARGE_ORCHESTRATOR, 
	ERROR, 
	TRACE_ID, 
	ACCEPTED_CHANNEL, 
	FUNCTIONAL_ERROR, 
	NOT_ACCEPTED_CHANNEL, 
	NOT_GSM, // ESTE ES EL QUE UTILIZO SUSTITUYENDO EL RECHARGE_ORCHESTRATOR
	EXCEPTION;
	//ORCHESTRATOR
}
